spring:
  application:
    name: secure-file-share
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/secure-file-share?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pub
